[package]
name = "docserver2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
crossbeam = "0.8.1"
hyper = { version = "0.14.16", features = ["full"] }
log = "0.4.14"
memmap2 = "0.5.0"
pretty_env_logger = "0.4.0"
regex = "1.5.4"
serde = { version = "1.0.133", features = ["derive"] }
sha2 = "0.10.1"
tokio = { version = "1", features = [
    "fs",
    "macros",
    "io-std",
    "io-util",
    "rt",
    "rt-multi-thread", # so examples can use #[tokio::main]
    "sync",
    "time",
    "test-util",
    "signal",
] }
toml = "0.5.8"
zstd = "0.9.2"
tera = "1"
